services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass123
    networks:
      - medical_net
    command: ["mongod", "--auth"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: migrateUser
      MONGO_PASSWORD: MigratePass123!
      MONGO_DB: Medical_db
    volumes:
      - .:/app
    networks:
      - medical_net

volumes:
  mongo-data:

networks:
  medical_net:
    driver: bridge
